version: "3"
services:
  web:
    build: .
    restart: always
    command: bash -c "python /code/manage.py makemigrations & python /code/manage.py migrate & python /code/manage.py startbot"
    volumes:
      - .:/code
    ports:
      - "8000:8000"


