version: '3.4'

services:

  db:
    hostname: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_DB=watcher
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: on-failure
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py migrate django_celery_beat && python manage.py startbot 0.0.0.0:8088"
    depends_on:
      - db
    expose:
      - "8088"
    hostname: app
    image: app-image
    restart: on-failure

  redis:
    image: "redis:alpine"
    command: redis-server --protected-mode no
    ports:
      - "6379:6379"
    expose:
      - "6379"
    environment:
      - REDIS_REPLICATION_MODE=master

  celery_worker1:
    #    command: sh -c "wait-for rabbitmq:5672 && wait-for app:8088 -- celery -A TheWatcher worker -c 10"
    command: sh -c "celery -A TheWatcher worker -c 10 -n wrk1"
    depends_on:
      - app
      - db
    #      - rabbitmq
    environment:
      - C_FORCE_ROOT=true
    hostname: celery_worker
    image: app-image
    restart: on-failure

  celery_worker2:
    #    command: sh -c "wait-for rabbitmq:5672 && wait-for app:8088 -- celery -A TheWatcher worker -c 10"
    command: sh -c "celery -A TheWatcher worker -c 10 -n wrk2"
    depends_on:
      - app
      - db
    #      - rabbitmq
    environment:
      - C_FORCE_ROOT=true
    hostname: celery_worker
    image: app-image
    restart: on-failure

  celery_worker3:
    #    command: sh -c "wait-for rabbitmq:5672 && wait-for app:8088 -- celery -A TheWatcher worker -c 10"
    command: sh -c "celery -A TheWatcher worker -c 10 -n wrk3"
    depends_on:
      - app
      - db
    #      - rabbitmq
    environment:
      - C_FORCE_ROOT=true
    hostname: celery_worker
    image: app-image
    restart: on-failure

  celery_worker4:
    #    command: sh -c "wait-for rabbitmq:5672 && wait-for app:8088 -- celery -A TheWatcher worker -c 10"
    command: sh -c "celery -A TheWatcher worker -c 10 -n wrk4"
    depends_on:
      - app
      - db
    #      - rabbitmq
    environment:
      - C_FORCE_ROOT=true
    hostname: celery_worker
    image: app-image
    restart: on-failure

  celery_worker5:
    #    command: sh -c "wait-for rabbitmq:5672 && wait-for app:8088 -- celery -A TheWatcher worker -c 10"
    command: sh -c "celery -A TheWatcher worker -c 10 -n wrk5"
    depends_on:
      - app
      - db
    #      - rabbitmq
    environment:
      - C_FORCE_ROOT=true
    hostname: celery_worker
    image: app-image
    restart: on-failure

  celery_beat:
    #    command: sh -c "wait-for rabbitmq:5672 && wait-for app:8088 -- celery -A TheWatcher beat -S django
    command: sh -c "celery -A TheWatcher beat -S django"
    depends_on:
      - app
      - db
    #      - rabbitmq
    hostname: celery_beat
    image: app-image
    restart: on-failure


volumes:
  postgresql-data: