# Generated by Django 3.0.8 on 2020-07-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=199, unique=True)),
                ('chat_name', models.CharField(max_length=199)),
                ('username', models.CharField(max_length=199)),
                ('lastname', models.CharField(max_length=199)),
                ('url', models.ManyToManyField(blank=True, related_name='urls', to='Bot.Site')),
            ],
        ),
    ]
