# Generated by Django 3.0.8 on 2020-07-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_auto_20200713_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
