# Generated by Django 3.0.8 on 2020-07-23 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_client_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='checking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='last_check',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
